[project]
name = "pederseo-server"
version = "1.0.0"
description = "Basic FastAPI server for Render deployment"
readme = "README.md"
authors = [
    { name = "Olaf Pedersen" }
]
requires-python = ">=3.12"
dependencies = [
    "pyjwt>=2.10.0",
    "fastapi>=0.115.0",
    "uvicorn[standard]>=0.30.0",
    "sqlmodel>=0.0.22",
    "supabase>=2.9.0",
    "psycopg[binary]>=3.3.5",
    "python-dotenv>=1.2.3",
    "alembic>=1.19.1",
]

[tool.uv]
package = false
