"""add mesa, item, player, photo, votes

Revision ID: 18967f44f3ff
Revises: f8f3e298ea29
Create Date: 2026-09-21 16:59:13.153637

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '18967f44f3ff'
down_revision: Union[str, Sequence[str], None] = 'f8f3e298ea29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mesa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('player',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('mesa_id', sa.Integer(), nullable=False),
    sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['mesa_id'], ['mesa.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('mesa_vote',
    sa.Column('voter_id', sa.Uuid(), nullable=False),
    sa.Column('target_mesa_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['target_mesa_id'], ['mesa.id'], ),
    sa.ForeignKeyConstraint(['voter_id'], ['player.user_id'], ),
    sa.PrimaryKeyConstraint('voter_id')
    )
    op.create_table('photo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('mesa_id', sa.Integer(), nullable=False),
    sa.Column('uploaded_by', sa.Uuid(), nullable=False),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ),
    sa.ForeignKeyConstraint(['mesa_id'], ['mesa.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['player.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('item_vote',
    sa.Column('voter_id', sa.Uuid(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('photo_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ),
    sa.ForeignKeyConstraint(['photo_id'], ['photo.id'], ),
    sa.ForeignKeyConstraint(['voter_id'], ['player.user_id'], ),
    sa.PrimaryKeyConstraint('voter_id', 'item_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('item_vote')
    op.drop_table('photo')
    op.drop_table('mesa_vote')
    op.drop_table('player')
    op.drop_table('mesa')
    op.drop_table('item')
    # ### end Alembic commands ###
